### PR TITLE
Fix tests and move packages around

### PR DESCRIPTION
**Pull request by dmpe**
In addition, it moves several packages up to the "Imports" because `Quandl` depends on them. I have also added myself as a contributor. I hope @RaymondMcT that you don't mind. 

Additionally, given `@import` statements I have added, there is now zero need to use :: in the code. See here: https://github.com/ropensci/onboarding/issues/17#issuecomment-116782430 (section Imports)

I have also fixed tests by adding my key. Otherwise, tests run quickly out of limit. Maybe you can add some new one which could be used only for this package ?

This may also be fixing #35 @hansthompson your input is welcome as well.

### CODE REVIEW

**Comment by dmpe** [comment]
Hi @RaymondMcT, 
any update on this PR ( #37 #36 ) ?

**Comment by dmpe** [comment]
@RaymondMcT 
any news ?

**Comment by RaymondMcT** [comment]
We are considering rewriting the whole package from the ground up. We would like it to stay stationary for the time being aside from major bug fixes.

**Comment by dmpe** [comment]
@RaymondMcT Understand. If you do consider rewriting the whole package, then please consider taking a look on my changes.
Thank you.

**Pull request closed without merging**
